blank_issues_enabled: false
contact_links:
  - name: Fonoster Community Support
    url: https://github.com/fonoster/discussions
    about: Please ask and answer Fonoster questions here.
  - name: Routr Community Support
    url: https://github.com/fonoster/routr/discussions
    about: Please ask and answer Routr questions here.
  - name: Discord Community
    url: https://discord.gg/4QWgSz4hTC
    about: Join our Discord community here.
